#!/usr/bin/env python3

import argparse
import subprocess
import time

import requests


def _main() -> None:
    argparser = argparse.ArgumentParser("Test the docker-compose application.")
    argparser.add_argument("file", type=str, help="The docker-compose file to test.")
    args = argparser.parse_args()

    try:
        subprocess.run(["docker-compose", f"--file={args.file}", "up", "--detach"])
        for _ in range(30):
            try:
                result = requests.get("http://localhost:8000")
                if result.status_code == 200:
                    break
                time.sleep(1)
            except requests.exceptions.ConnectionError:
                pass
    finally:
        subprocess.run(["docker-compose", f"--file={args.file}", "logs"])
        subprocess.run(["docker-compose", f"--file={args.file}", "down"])


if __name__ == "__main__":
    _main()
