# Files containing the definition of all services used in the
# Docker Compose file where we have coherent compositing.

version: '3.4'
services:
  redis:
    image: docker.io/library/redis:7.2.4
    restart: unless-stopped
    volumes:
      - ${REDIS_DATA_VOLUME}:/data

  postgres:
    image: docker.io/library/postgres:16.2
    restart: unless-stopped
    volumes:
      - ${POSTGRES_DATA_VOLUME}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_INITDB_ARGS
      - POSTGRES_INITDB_WALDIR
      - POSTGRES_HOST_AUTH_METHOD
      - PGDATABASE=${POSTGRES_DB}
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGHOST=localhost
      - PGPORT=5432

  postgres-vacuum:
    image: docker.io/library/postgres:16.2
    command:
      - psql
      - -c
      - ALTER DATABASE ${POSTGRES_DB} REFRESH COLLATION VERSION; VACUUM FULL ANALYZE; REINDEX DATABASE ${POSTGRES_DB};
    environment:
      - PGDATABASE=${POSTGRES_DB}
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGHOST=db
      - PGPORT=5432

  postgres-upgrade:
    image: tianon/postgres-upgrade:${POSTGRES_UPGRADE_OLD}-to-${POSTGRES_UPGRADE_NEW}
    command: ${POSTGRES_UPGRADE_COMMAND}
    volumes:
      - ${POSTGRES_UPGRADE_OLD_VOLUME}:/var/lib/postgresql/${POSTGRES_UPGRADE_OLD}/data
      - ${POSTGRES_UPGRADE_NEW_VOLUME}:/var/lib/postgresql/${POSTGRES_UPGRADE_NEW}/data
    environment:
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGDATABASE=${POSTGRES_DB}
      - POSTGRES_INITDB_ARGS=--username=${POSTGRES_USER}

  mariadb:
    image: docker.io/library/mariadb:11.3.2
    restart: unless-stopped
    volumes:
      - ${MARIADB_DATA_VOLUME}:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=paperless
      - MARIADB_USER=paperless
      - MARIADB_PASSWORD=paperless
      - MARIADB_ROOT_PASSWORD=paperless
      - MARIADB_ROOT_PASSWORD_HASH
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
      - MARIADB_RANDOM_ROOT_PASSWORD
      - MARIADB_ROOT_HOST
      - MARIADB_MYSQL_LOCALHOST_USER
      - MARIADB_MYSQL_LOCALHOST_GRANTS
      - MARIADB_PASSWORD_HASH
      - MARIADB_INITDB_SKIP_TZINFO
      - MARIADB_AUTO_UPGRADE
      - MARIADB_DISABLE_UPGRADE_BACKUP

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.8.4
    restart: unless-stopped
    ports:
      - ${PAPERLESS_PORT}:${PAPERLESS_INNER_PORT}
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:${PAPERLESS_INNER_PORT}
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ${PAPERLESS_DATA_VOLUME}:/usr/src/paperless/data
      - ${PAPERLESS_MEDIA_VOLUME}:/usr/src/paperless/media
      - ${PAPERLESS_EXPORT_VOLUME}:/usr/src/paperless/export
      - ${PAPERLESS_CONSUME_VOLUME}:/usr/src/paperless/consume
    # Complete list: https://github.com/paperless-ngx/paperless-ngx/blob/main/paperless.conf.example
    # Documentation: https://docs.paperless-ngx.com/configuration/
    environment:
      - PAPERLESS_REDIS=redis://broker:6379
      - PAPERLESS_ALLOWED_HOSTS
      - PAPERLESS_ADMIN_MAIL
      - PAPERLESS_ADMIN_PASSWORD
      - PAPERLESS_ADMIN_USER
      - PAPERLESS_AUDIT_LOG_ENABLED
      - PAPERLESS_AUTO_LOGIN_USERNAME
      - PAPERLESS_BIND_ADDR
      - PAPERLESS_CERTIFICATE_LOCATION
      - PAPERLESS_CONSUMER_DELETE_DUPLICATES
      - PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE
      - PAPERLESS_CONSUMER_ENABLE_BARCODES
      - PAPERLESS_CONSUMER_INOTIFY_DELAY
      - PAPERLESS_CONSUMER_POLLING
      - PAPERLESS_CONSUMER_POLLING_DELAY
      - PAPERLESS_CONSUMER_POLLING_RETRY_COUNT
      - PAPERLESS_CONSUMER_RECURSIVE
      - PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS
      - PAPERLESS_CONSUMER_TAG_SEPARATOR
      - PAPERLESS_CONSUMER_WATCHED_DIRS
      - PAPERLESS_CONSUMER_WATCHED_DIRS_RECURSIVE
      - PAPERLESS_CONSUMER_WATCHED_DIRS_TAG
      - PAPERLESS_CONSUMER_WATCHED_DIRS_TAG_RECURSIVE
      - PAPERLESS_CONSUMER_WATCHED_DIRS_TAG_SEPARATOR
      - PAPERLESS_CONSUMER_WATCHED_DIRS_TAG_SEPARATOR_RECURSIVE
      - PAPERLESS_CONVERT_BINARY
      - PAPERLESS_CONVERT_MEMORY_LIMIT
      - PAPERLESS_CONVERT_TMPDIR
      - PAPERLESS_COOKIE_PREFIX
      - PAPERLESS_CSRF_TRUSTED_ORIGINS
      - PAPERLESS_DATA_DIR
      - PAPERLESS_DATE_ORDER
      - PAPERLESS_DBENGINE
      - PAPERLESS_DBHOST
      - PAPERLESS_DBNAME
      - PAPERLESS_DBPASS
      - PAPERLESS_DBPORT
      - PAPERLESS_DBSSLMODE
      - PAPERLESS_DBTIMEOUT
      - PAPERLESS_DBUSER
      - PAPERLESS_DEBUG
      - PAPERLESS_EMAIL_CERTIFICATE_LOCATION
      - PAPERLESS_EMAIL_HOST
      - PAPERLESS_EMAIL_HOST_PASSWORD
      - PAPERLESS_EMAIL_HOST_USER
      - PAPERLESS_EMAIL_PORT
      - PAPERLESS_EMAIL_TASK_CRON
      - PAPERLESS_EMAIL_USE_SSL
      - PAPERLESS_EMAIL_USE_TLS
      - PAPERLESS_ENABLE_FLOWER
      - PAPERLESS_ENABLE_HTTP_REMOTE_USER
      - PAPERLESS_ENABLE_NLTK
      - PAPERLESS_ENABLE_UPDATE_CHECK
      - PAPERLESS_FILENAME_DATE_ORDER
      - PAPERLESS_FILENAME_FORMAT
      - PAPERLESS_FILENAME_FORMAT_REMOVE_NONE
      - PAPERLESS_FILENAME_PARSE_TRANSFORMS
      - PAPERLESS_FORCE_SCRIPT_NAME
      - PAPERLESS_GS_BINARY
      - PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME
      - PAPERLESS_IGNORE_DATES
      - PAPERLESS_INDEX_TASK_CRON
      - PAPERLESS_LETSENCRYPT_EMAIL
      - PAPERLESS_LOGGING_DIR
      - PAPERLESS_LOGROTATE_MAX_BACKUPS
      - PAPERLESS_LOGROTATE_MAX_SIZE
      - PAPERLESS_LOGOUT_REDIRECT_URL
      - PAPERLESS_MAX_PAGE_SIZE
      - PAPERLESS_MEDIA_ROOT
      - PAPERLESS_NLTK_DIR
      - PAPERLESS_NUMBER_OF_SUGGESTED_DATES
      - PAPERLESS_OCR_CLEAN
      - PAPERLESS_OCR_DESKEW
      - PAPERLESS_OCR_IMAGE_DPI
      - PAPERLESS_OCR_LANGUAGE
      - PAPERLESS_OCR_MAX_IMAGE_PIXELS
      - PAPERLESS_OCR_MODE
      - PAPERLESS_OCR_OUTPUT_TYPE
      - PAPERLESS_OCR_PAGES
      - PAPERLESS_OCR_ROTATE_PAGES
      - PAPERLESS_OCR_ROTATE_PAGES_THRESHOLD
      - PAPERLESS_OCR_USER_ARGS
      - PAPERLESS_PDFINFO_BINARY
      - PAPERLESS_PORT
      - PAPERLESS_POST_CONSUME_SCRIPT
      - PAPERLESS_PRE_CONSUME_SCRIPT
      - PAPERLESS_SANITY_TASK_CRON
      - PAPERLESS_SECRET_KEY
      - PAPERLESS_STATICDIR
      - PAPERLESS_STATIC_URL
      - PAPERLESS_TASK_WORKERS
      - PAPERLESS_THREADS_PER_WORKER
      - PAPERLESS_THUMBNAIL_FONT_NAME
      - PAPERLESS_TIME_ZONE
      - PAPERLESS_TIKA_ENABLED
      - PAPERLESS_TIKA_ENDPOINT
      - PAPERLESS_TIKA_GOTENBERG_ENDPOINT
      - PAPERLESS_TRAIN_TASK_CRON
      - PAPERLESS_TRASH_DIR
      - PAPERLESS_URL
      - PAPERLESS_WEBSERVER_WORKERS
      - USERMAP_UID
      - USERMAP_GID
      - OMP_SCHEDULE
      - OMP_NUM_THREADS
      - OMP_DYNAMIC
      - OMP_PROC_BIND
      - OMP_PLACES
      - OMP_STACKSIZE
      - OMP_WAIT_POLICY
      - OMP_MAX_ACTIVE_LEVELS
      - OMP_NESTED
      - OMP_THREAD_LIMIT
      - OMP_CANCELLATION
      - OMP_DISPLAY_ENV
      - OMP_DISPLAY_AFFINITY
      - OMP_AFFINITY_FORMAT
      - OMP_DEFAULT_DEVICE
      - OMP_MAX_TASK_PRIORITY
      - OMP_TARGET_OFFLOAD
      - OMP_TOOL
      - OMP_TOOL_LIBRARIES
      - OMP_DEBUG
      - OMP_ALLOCATOR

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.4.0
    restart: unless-stopped
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - gotenberg
      - --chromium-disable-javascript=true
      - --chromium-allow-list=file:///tmp/.*

  tika:
    image: ghcr.io/paperless-ngx/tika:2.9.1-minimal
    restart: unless-stopped
