# In addition to that, this docker-compose file adds the following optional
# configurations:
#
# - Instead of SQLite (default), PostgreSQL is used as the database server.

version: '3.4'
services:
  broker:
    extends:
      file: docker-compose.lib.yaml
      service: redis

  db:
    extends:
      file: docker-compose.lib.yaml
      service: postgres

  postgres-upgrade:
    extends:
      file: docker-compose.lib.yaml
      service: postgres-upgrade

  paperless:
    extends:
      file: docker-compose.lib.yaml
      service: paperless
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db

volumes:
  data:
  media:
  pgdata:
  redisdata:
  pgdata-9:
  pgdata-10:
  pgdata-11:
  pgdata-12:
  pgdata-13:
  pgdata-14:
  pgdata-15:
