name: Continuous integration

on:
  pull_request:
  push:
    branches:
      - master
      - '[0-9]+.[0-9]+'
    tags:
      - '*'

permissions:
  contents: write

env:
  HAS_SECRETS: ${{ secrets.HAS_SECRETS }}

jobs:
  main:
    name: Continuous integration
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    if: "!startsWith(github.event.head_commit.message, '[skip ci] ')"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install pre-commit
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: "pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}\npre-commit-"
      - run: pre-commit run --all-files --color=always
      - run: git diff --exit-code --patch > /tmp/pre-commit.patch; git diff --color; git reset --hard || true
        if: failure()

      - uses: actions/upload-artifact@v4
        with:
          name: Apply pre-commit fix.patch
          path: /tmp/pre-commit.patch
          retention-days: 1
        if: failure()
      - run: pip install requests
      - run: .github/test-app docker-compose.postgres.yaml
      - run: .github/test-app docker-compose.postgres-tika.yaml
      - run: .github/test-app docker-compose.mariadb.yaml
      - run: .github/test-app docker-compose.mariadb-tika.yaml
      - run: .github/test-app docker-compose.sqlite.yaml
      - run: .github/test-app docker-compose.sqlite-tika.yaml
