name: Continuous integration

on:
  push:
    branches:
      - master
      - '[0-9]+.[0-9]+'
    tags:
      - '*'

jobs:
  main:
    runs-on: ubuntu-22.04
    name: Continuous integration
    timeout-minutes: 15
    if: "!startsWith(github.event.head_commit.message, '[skip ci] ')"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: pip install pre-commit
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: "pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}\npre-commit-"
      - run: pre-commit run --all-files
      - run: git diff
        if: failure()

      - run: docker compose --file=docker-compose.postgres.yaml up --detach
      - run: curl --fail --retry 10 --retry-delay 5 --retry-connrefused http://localhost:8000
      - run: docker compose --file=docker-compose.postgres.yaml logs
        if: failure()
